---
version: "3.8"

services:

  postgres:
    image: postgres:alpine
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    healthcheck:
      test: pg_isready -d todo -U postgres 
      interval: 5s
      timeout: 10s
      retries: 36
    ports:
      - "5432:5432"
    volumes:
      - .db/postgres:/var/lib/postgresql/data
    networks:
      todo:
        ipv4_address: 10.101.0.5


networks:
  todo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.101.0.0/16
